version: '2'
services:
  141021-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "18000:80"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  141021-eureka:
    image: 141021/soa-lab-eureka
    labels:
      - "traefik.port=8761"
      - "traefik.backend=141021-eureka"
      - "traefik.frontend.rule=Host:my-eureka.dck.mojserver.mk"
    expose:
      - "8761"
    ports:
      - "8761:8761"


  141021-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: demo
    volumes:
      - 141021-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  141021-app:
    image: 141021/soa-lab-app
    labels:
      - "traefik.port=8080"
      - "traefik.backend=141021-app"
      - "traefik.frontend.rule=Host:141021-app.dck.mojserver.mk"
    links:
      - 141021-mysql
      - 141021-eureka
    depends_on:
      - 141021-mysql
      - 141021-traefik
      - 141021-eureka
volumes:
  141021-datavolume: {}